version: '3.4'
services:

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.external-url=http://192.168.1.133:9090"
    ports:
      - "9090:9090"
    read_only: true      
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

volumes:
  prometheus:
    driver: local
  prometheus_data:
    driver: local
  grafana:
    driver: local
  grafana_data:
    driver: local
  alertmanager:
    driver: local